# Generated by Django 4.2.5 on 2023-09-09 10:47

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NippoModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company", models.CharField(max_length=100)),
                ("company_id", models.CharField(max_length=100)),
                ("company_password", models.CharField(max_length=100)),
            ],
        ),
    ]
